/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.HoaDon;
import Model.HoaDonCT;
import Model.SanPhamCTSale;
import Repository.HoaDonCTRepository;
import Repository.HoaDonRepository;
import Repository.InformationDAO;
import Repository.SPCTSaleRepository;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BanHangView extends javax.swing.JPanel {

    private SPCTSaleRepository serviceSPCT = new SPCTSaleRepository();
    private HoaDonRepository serviceHD = new HoaDonRepository();
    private HoaDonCTRepository serviceHDCT = new HoaDonCTRepository();
    InformationDAO informationDAO = new InformationDAO();
    private DefaultTableModel mol = new DefaultTableModel();

    String email, name;

    public BanHangView(String name, String email) {
        initComponents();
        this.email = email;
        this.name = name;
        txt_TenNV.setText(name);
        this.fillTableSPCT(serviceSPCT.getDataSPCT(txt_TimKiem.getText().trim()));
        this.fillTableHD(serviceHD.getDaTaHD()); // fill hóa đơn chờ  
        System.out.println(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioHang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDonCT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        HoaDon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hoaDon = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_SPCT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Vocher = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_TienSauGiamGia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbo_hinhThuc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_tienMat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_tienCK = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tienThua = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GioHang.setBackground(new java.awt.Color(255, 255, 255));
        GioHang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        GioHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_HoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SPCT", "Tên ", "Màu sắc", "Chất liệu", "Size", "Số lượng ", "Giá bán", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDonCT);

        GioHang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 670, 130));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-edit-24.png"))); // NOI18N
        GioHang.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 40, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-remove-24.png"))); // NOI18N
        GioHang.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 40, -1));

        add(GioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 215, 750, 170));

        HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        HoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        HoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Tên nhân viên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_hoaDon);

        HoaDon.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 670, 150));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-24.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        HoaDon.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 40, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-remove-24.png"))); // NOI18N
        HoaDon.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 40, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-24.png"))); // NOI18N
        HoaDon.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 40, -1));

        add(HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, 750, 190));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbl_SPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SPCT", "Tên SP", "Màu sắc", "Thương hiệu", "Chất liệu", "Xuất xứ", "Size", "Số lượng tồn ", "Giá bán "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_SPCT);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_TimKiem.setForeground(java.awt.Color.red);
        txt_TimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 400, 753, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Bán hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Thông tin khách hàng ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã KH");

        txt_maKH.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên KH");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("SĐT");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Cập Nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-list-24.png"))); // NOI18N

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Thanh Toán");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red), "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã HĐ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        txt_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_MaHD.setForeground(java.awt.Color.red);
        txt_MaHD.setEnabled(false);
        jPanel4.add(txt_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 24, 151, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tên NV");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_TenNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_TenNV.setForeground(java.awt.Color.red);
        txt_TenNV.setEnabled(false);
        jPanel4.add(txt_TenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 151, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tổng Tiền");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_TongTien.setEnabled(false);
        jPanel4.add(txt_TongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Voucher");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel4.add(txt_Vocher, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tiền sau giảm giá");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 107, -1));

        txt_TienSauGiamGia.setEnabled(false);
        jPanel4.add(txt_TienSauGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 222, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Hình thức");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cbo_hinhThuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbo_hinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn hình thức thanh toán", "Chuyển Khoản", "Tiền Mặt" }));
        cbo_hinhThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hinhThucActionPerformed(evt);
            }
        });
        jPanel4.add(cbo_hinhThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 153, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Tiền mặt");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 281, -1, -1));

        txt_tienMat.setEnabled(false);
        txt_tienMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tienMatKeyReleased(evt);
            }
        });
        jPanel4.add(txt_tienMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 278, 141, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tiền CK");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 315, -1, -1));

        txt_tienCK.setEnabled(false);
        jPanel4.add(txt_tienCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 312, 141, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Tiền thừa");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 349, -1, -1));

        txt_tienThua.setEnabled(false);
        jPanel4.add(txt_tienThua, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 346, 141, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-confirm-24.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 40, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 260, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKeyReleased
        // Search Product 
        String key = txt_TimKiem.getText().trim();
        this.fillTableSPCT(serviceSPCT.getDataSPCT(key));
    }//GEN-LAST:event_txt_TimKiemKeyReleased

    private void tbl_hoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoaDonMouseClicked
        // Click hiện thị hóa đơn chi tiết , hiện thị thông tin hóa đơn lên form 
        int index = tbl_hoaDon.getSelectedRow();
        if (index < -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn ! ");
            return;
        }
        cbo_hinhThuc.setSelectedIndex(0);
        txt_tienCK.setText("");
        int idHoaDon = (Integer) this.tbl_hoaDon.getValueAt(index, 0);
        this.fillTableHDCT(serviceHDCT.getHDCT(idHoaDon));
        this.showInformation();
    }//GEN-LAST:event_tbl_hoaDonMouseClicked

    private void cbo_hinhThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hinhThucActionPerformed
        // Chọn phương thức thanh toán 
        this.choicePayMents();
    }//GEN-LAST:event_cbo_hinhThucActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Tạo hóa đơn chờ 
        this.createBill();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_tienMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tienMatKeyReleased
        // Nhận tiền mặt của khách 
        try {
            if (txt_tienMat.getText().isEmpty()) {
                txt_tienThua.setText("");
            }
            NumberFormat vndFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
            BigDecimal sumMonney = (BigDecimal.valueOf(Double.valueOf(txt_TienSauGiamGia.getText())));
            BigDecimal moneyReceived = BigDecimal.valueOf(Double.valueOf(txt_tienMat.getText()));
            BigDecimal change = moneyReceived.subtract(sumMonney);
            txt_tienThua.setText(vndFormat.format(change));
        } catch (Exception e) {
            txt_tienThua.setText("");
        }
    }//GEN-LAST:event_txt_tienMatKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GioHang;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JComboBox<String> cbo_hinhThuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_HoaDonCT;
    private javax.swing.JTable tbl_SPCT;
    private javax.swing.JTable tbl_hoaDon;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TienSauGiamGia;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TongTien;
    private javax.swing.JTextField txt_Vocher;
    private javax.swing.JTextField txt_maKH;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tienCK;
    private javax.swing.JTextField txt_tienMat;
    private javax.swing.JTextField txt_tienThua;
    // End of variables declaration//GEN-END:variables

    // fill table sản phẩm chi tiết 
    private void fillTableSPCT(List<SanPhamCTSale> list) {
        mol = (DefaultTableModel) tbl_SPCT.getModel();
        mol.setRowCount(0);
        for (SanPhamCTSale x : list) {
            mol.addRow(new Object[]{
                x.getMaSPCT(),
                x.getTenSP(),
                x.getTenMauSac(),
                x.getTenThuongHieu(),
                x.getTenChatLieu(),
                x.getTenXuatXu(),
                x.getSize(),
                x.getSoLuong(),
                x.getGiaBan()
            });
        }
    }

    // fill table hóa đơn
    private void fillTableHD(List<HoaDon> list) {
        mol = (DefaultTableModel) tbl_hoaDon.getModel();
        mol.setRowCount(0);
        for (HoaDon x : list) {
            mol.addRow(new Object[]{
                x.getIdHoaDon(),
                x.getTenKH(),
                x.getTenNV(),
                x.isTrangThai() ? "Đã thanh toán" : "Chờ thanh toán"
            });
        }
    }

    // fill table hóa đơn chi tiết 
    private void fillTableHDCT(List<HoaDonCT> list) {
        mol = (DefaultTableModel) tbl_HoaDonCT.getModel();
        mol.setRowCount(0);
        for (HoaDonCT x : list) {
            mol.addRow(new Object[]{
                x.getMaHoaDonChiTiet(),
                x.getTenSanPham(),
                x.getTenMauSac(),
                x.getTenChatLieu(),
                x.getSize(),
                x.getSoLuong(),
                x.getGiaBan(),
                x.getDonGia()
            });
        }
    }

    // Click show thông tin lên form 
    private void showInformation() {
        int index = tbl_hoaDon.getSelectedRow();
        HoaDon hd = serviceHD.getDaTaHD().get(index);
        txt_maKH.setText(String.valueOf(hd.getIdKhachHang()));
        txt_TenKH.setText(hd.getTenKH());
        txt_MaHD.setText(String.valueOf(hd.getIdHoaDon()));
        txt_TongTien.setText(hd.getThanhTien().toString());
        txt_TienSauGiamGia.setText(hd.getTienSauGiamGia().toString());
    }

    // Chọn hình thức thanh toán 
    private void choicePayMents() {
        int index = cbo_hinhThuc.getSelectedIndex();
        if (index == 2) { // Tiền mặt
            txt_tienMat.setEnabled(true);
            txt_tienThua.setEnabled(true);
            txt_tienCK.setText("");
        } else { // chuyển khoản 
            txt_tienMat.setEnabled(false);
            txt_tienThua.setEnabled(false);
            txt_tienCK.setEnabled(false);
            String monney = txt_TienSauGiamGia.getText();
            txt_tienCK.setText(monney);
        }
    }

    // Tạo hóa đơn chờ 
    private void createBill() {
        int count = tbl_hoaDon.getRowCount();
        if (count <= 10) {
            serviceHD.createBill(informationDAO.getIDNVByEmail(email));
            this.fillTableHD(serviceHD.getDaTaHD());
        } else {
            JOptionPane.showMessageDialog(this, "Số lượng hóa đơn không được quá 10 ! ");
        }

    }
}
