/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String email, nameNV;
    int chucVu = 9;

    public Main(String email, String nameNV, int chucVu) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.email = email;
        this.nameNV = nameNV;
        this.chucVu = chucVu;
        lblNhanVien.setText(nameNV);
        setColor(lbl_Trangchu);
        showPanel(new TrangChuView());
        if (chucVu == 1) {
            lblChucVu.setText(" ADMIN");
        } else {
            lblChucVu.setText(" NHÂN VIÊN");
        }
        // System.out.println(chucVu);

    }

    private Main() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    @Override
    public void paintComponents(Graphics gp) {
        Graphics2D g2 = (Graphics2D) gp;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#8360c3"), 0, getHeight(), Color.decode("#2ebf91"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponents(gp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnDKM = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenuItem();
        Panel_Show = new javax.swing.JPanel();
        gradientColor1 = new ColorGradient2D.GradientColor();
        jLabel1 = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lbl_Trangchu = new javax.swing.JLabel();
        lbl_BanHang = new javax.swing.JLabel();
        lbl_SanPham = new javax.swing.JLabel();
        lbl_HoaDon = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_KhachHang = new javax.swing.JLabel();
        lbl_KhuyenMai = new javax.swing.JLabel();
        lbl_thongke = new javax.swing.JLabel();

        mnDKM.setText("Đổi mật khẩu");
        mnDKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDKMActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnDKM);

        mnThoat.setText("Thoát");
        mnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThoatActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnThoat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng BoLyBop");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Show.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Show.setPreferredSize(new java.awt.Dimension(1090, 650));
        Panel_Show.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Panel_Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 0, 1170, -1));

        gradientColor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-100 (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gradientColor1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, 80));

        lblNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(255, 102, 102));
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("Nhân Viên ");
        gradientColor1.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, -1));

        lblChucVu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 102, 102));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Chức vụ ");
        gradientColor1.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, -1));

        lbl_Trangchu.setBackground(new java.awt.Color(73, 186, 245));
        lbl_Trangchu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Trangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Trangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-24.png"))); // NOI18N
        lbl_Trangchu.setText("Trang chủ");
        lbl_Trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TrangchuMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_Trangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 224, 62));

        lbl_BanHang.setBackground(new java.awt.Color(73, 186, 245));
        lbl_BanHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_BanHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-fast-cart-24.png"))); // NOI18N
        lbl_BanHang.setText("Bán hàng");
        lbl_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BanHangMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 57));

        lbl_SanPham.setBackground(new java.awt.Color(73, 186, 245));
        lbl_SanPham.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_SanPham.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-shoe-24.png"))); // NOI18N
        lbl_SanPham.setText("Sản Phẩm");
        lbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SanPhamMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 57));

        lbl_HoaDon.setBackground(new java.awt.Color(73, 186, 245));
        lbl_HoaDon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_HoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-bill-24.png"))); // NOI18N
        lbl_HoaDon.setText("Hóa Đơn");
        lbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HoaDonMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 57));

        lbl_NhanVien.setBackground(new java.awt.Color(73, 186, 245));
        lbl_NhanVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-staff-24.png"))); // NOI18N
        lbl_NhanVien.setText("Nhân Viên");
        lbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 224, 57));

        lbl_KhachHang.setBackground(new java.awt.Color(73, 186, 245));
        lbl_KhachHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_KhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-client-24.png"))); // NOI18N
        lbl_KhachHang.setText("Khách Hàng");
        lbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 57));

        lbl_KhuyenMai.setBackground(new java.awt.Color(73, 186, 245));
        lbl_KhuyenMai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_KhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        lbl_KhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_KhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-voucher-24.png"))); // NOI18N
        lbl_KhuyenMai.setText("Khuyến Mãi");
        lbl_KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhuyenMaiMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_KhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 230, 57));

        lbl_thongke.setBackground(new java.awt.Color(73, 186, 245));
        lbl_thongke.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_thongke.setForeground(new java.awt.Color(255, 255, 255));
        lbl_thongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-analytics-24.png"))); // NOI18N
        lbl_thongke.setText("Thống Kê");
        lbl_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_thongkeMouseClicked(evt);
            }
        });
        gradientColor1.add(lbl_thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 230, 57));

        getContentPane().add(gradientColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_TrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TrangchuMouseClicked
        // Click trang chủ 
        setColor(lbl_Trangchu);

        resetColor(lbl_thongke);
        resetColor(lbl_BanHang);
        resetColor(lbl_SanPham);
        resetColor(lbl_HoaDon);
        resetColor(lbl_KhachHang);
        resetColor(lbl_NhanVien);
        resetColor(lbl_KhuyenMai);
        showPanel(new TrangChuView());
    }//GEN-LAST:event_lbl_TrangchuMouseClicked

    private void lbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SanPhamMouseClicked
        // Click sản phẩm 
        if (chucVu == 1) {
            setColor(lbl_SanPham);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_thongke);
            resetColor(lbl_HoaDon);
            resetColor(lbl_KhachHang);
            resetColor(lbl_NhanVien);
            resetColor(lbl_KhuyenMai);
            showPanel(new SanPhamView());
        } else if (chucVu == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập !");
        }

    }//GEN-LAST:event_lbl_SanPhamMouseClicked

    private void lbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HoaDonMouseClicked
        // Click hóa đơn 
        if (chucVu == 1 || chucVu == 0) {
            setColor(lbl_HoaDon);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_SanPham);
            resetColor(lbl_thongke);
            resetColor(lbl_KhachHang);
            resetColor(lbl_NhanVien);
            resetColor(lbl_KhuyenMai);
            showPanel(new HoaDonView());
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập ! ");
        }
    }//GEN-LAST:event_lbl_HoaDonMouseClicked

    private void lbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseClicked
        // Click Nhân Viên 
        if (chucVu == 1) {
            setColor(lbl_NhanVien);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_SanPham);
            resetColor(lbl_HoaDon);
            resetColor(lbl_KhachHang);
            resetColor(lbl_thongke);
            resetColor(lbl_KhuyenMai);
            showPanel(new NhanVienView());
        } else if (chucVu == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập !");
        }
    }//GEN-LAST:event_lbl_NhanVienMouseClicked

    private void lbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseClicked
        // CLick khách hàng 
        if (chucVu == 1 || chucVu == 0) {
            setColor(lbl_KhachHang);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_SanPham);
            resetColor(lbl_HoaDon);
            resetColor(lbl_thongke);
            resetColor(lbl_NhanVien);
            resetColor(lbl_KhuyenMai);
            showPanel(new KhachHangView());
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập ! ");
        }
    }//GEN-LAST:event_lbl_KhachHangMouseClicked

    private void lbl_KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhuyenMaiMouseClicked
        // Click khuyến mãi 
        if (chucVu == 1) {
            setColor(lbl_KhuyenMai);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_SanPham);
            resetColor(lbl_HoaDon);
            resetColor(lbl_KhachHang);
            resetColor(lbl_NhanVien);
            resetColor(lbl_thongke);
            showPanel(new KhuyenMaiView());
        }
        else if(chucVu == 0){
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này !");
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập ! ");
        }
    }//GEN-LAST:event_lbl_KhuyenMaiMouseClicked

    private void lbl_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_thongkeMouseClicked
        // CLick thống kê 
        if (chucVu == 1) {
            setColor(lbl_thongke);

            resetColor(lbl_Trangchu);
            resetColor(lbl_BanHang);
            resetColor(lbl_SanPham);
            resetColor(lbl_HoaDon);
            resetColor(lbl_KhachHang);
            resetColor(lbl_NhanVien);
            resetColor(lbl_KhuyenMai);
            showPanel(new ThongKeView());
        } else if (chucVu == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền sử dụng chức năng này");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập !");
        }
    }//GEN-LAST:event_lbl_thongkeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPopupMenu1.show(evt.getComponent(), -20, 60);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void mnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThoatActionPerformed
        // Thoát
        LoginView lg = new LoginView();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnThoatActionPerformed

    private void mnDKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDKMActionPerformed
//         Đổi mật khẩu
//        DoiMK_View dmk = new DoiMK_View(email);
//        dmk.setVisible(true);
    }//GEN-LAST:event_mnDKMActionPerformed

    private void lbl_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BanHangMouseClicked
        // Click bán hàng
        if (chucVu == 1 || chucVu == 0) {
            setColor(lbl_BanHang);

            resetColor(lbl_Trangchu);
            resetColor(lbl_thongke);
            resetColor(lbl_SanPham);
            resetColor(lbl_HoaDon);
            resetColor(lbl_KhachHang);
            resetColor(lbl_NhanVien);
            resetColor(lbl_KhuyenMai);
         showPanel(new BanHangView(nameNV, email));
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập ! ");
        }
    }//GEN-LAST:event_lbl_BanHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Show;
    private ColorGradient2D.GradientColor gradientColor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lbl_BanHang;
    private javax.swing.JLabel lbl_HoaDon;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_KhuyenMai;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_SanPham;
    private javax.swing.JLabel lbl_Trangchu;
    private javax.swing.JLabel lbl_thongke;
    private javax.swing.JMenuItem mnDKM;
    private javax.swing.JMenuItem mnThoat;
    // End of variables declaration//GEN-END:variables

    public void setColorJpanel(JPanel pane) {
        pane.setBackground(new java.awt.Color(255, 255, 255));
    }

    public void resetColorJpane(JPanel pane) {
        pane.setBackground(new java.awt.Color(73, 186, 245));
    }

    public void setColor(JLabel label) {
        label.setForeground(Color.black);
    }

    public void resetColor(JLabel label) {
        label.setForeground(Color.white);
    }

    public void showPanel(JPanel panel) {
        Panel_Show.removeAll();
        Panel_Show.add(panel);
        Panel_Show.revalidate();
    }

}
